### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by DIYer22** [zocker-160/blender-bpy#1]
Python 3.7.4 

```
import bpy

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /home/dl/junk/blender_as_module/Blender-bpy/bpy.so)
```

What should I do?

**Comment by zocker-160** [comment]
The binary build is probably made for a newer GLIBC version, which is causing the error you have.

What distro are you on and which Kernel version are you using?

If you tell me that, I can compile a new package for you.

**Comment by DIYer22** [comment]
I finally decide to using your bpy in docker by
```
docker run --rm -it zocker160/blender-bpy bash
```
Thank you anyway!

**Comment by zocker-160** [comment]
ok fair that works too :ok_hand: 

(will update that container to a newer blender version soon)

**Comment by DIYer22** [comment]
I also tried update that docker, but failed. Look forward to the newer docker.

**Comment by zocker-160** [comment]
I pushed an update, latest stable version is now available under `zocker160/blender-bpy:stable`
Latest master under `zocker160/blender-bpy:beta`

There are a few errors during import of bpy, but it should work anyway. I could not find a solution for the missing libs yet, but they are mostly import / export related, so you should be fine if you don't need those.

**Comment by DIYer22** [comment]
🎉🎉🎉
